# Numpy

### NumPy, or the Numeric Python library, is useful for working with arrays, which are data structures that store values of the same data type. 
### NumPy arrays are similar to Python lists except that they require less memory and are usually faster because they use optimized, precompiled C code

In [14]:
 import numpy as np
jeff_salary = [2700,3000,3000]
nick_salary = [2600,2800,2800]
tom_salary = [2300,2500,2500]
base_salary = np.array([jeff_salary, nick_salary,tom_salary])
print(base_salary)

[[2700 3000 3000]
 [2600 2800 2800]
 [2300 2500 2500]]


### This is a 2D array. It has two axes, which are indexed by integers,starting with 0. Axis 0 runs vertically downward across the array’s rows, while axis 1 runs horizontally across the columns.

### You can follow the same process to create an array containing the employees’ monthly bonuses:

In [18]:
jeff_bonus = [500,400,400]
nick_bonus = [600,300,400]
tom_bonus = [200,500,400]
bonus = np.array([jeff_bonus, nick_bonus, tom_bonus])

# Performing Element-Wise Operations

### It’s easy to perform element-wise operations on multiple NumPy arrays of the same dimensions. For example, you can add the base_salary and bonus arrays together to determine the total amount paid each month to each employee:

In [23]:
salary_bonus = base_salary + bonus
print(type(salary_bonus))
print(salary_bonus)

<class 'numpy.ndarray'>
[[3200 3400 3400]
 [3200 3100 3200]
 [2500 3000 2900]]


### As you can see, the addition operation is a one-liner. The resulting dataset is a NumPy array too, in which each element is the sum of the corresponding elements in the base_salary and bonus array

# Using NumPy Statistical Functions

### NumPy’s statistical functions allow you to analyze the contents of an array. For example, you can find the maximum value of an entire array or the maximum value of an array along a given axis. 

### Let’s say you want to find the maximum value in the salary_bonus array you created in the previous section. You can do this with the NumPy array’s max( ) function:

In [37]:
print(salary_bonus.max())

3400


### NumPy can also find the maximum value of an array along a given axis. If you want to determine the maximum amount paid to each employee in the past three months, you can use NumPy’s amax( ) function, as shown here:

In [41]:
print(np.amax(salary_bonus, axis = 1))

[3400 3200 3000]


### By specifying axis = 1, you instruct amax( ) to search horizontally across the columns for a maximum in the salary_bonus array, thus applying the function across each row. This calculates the maximum monthly amount paid to each employee in the past three months: