In [6]:
import numpy as np

In [8]:
jeff_salary = [2700,3000,3000]
nick_salary = [2600,2800,2800]
tom_salary = [2300,2500,2500]
base_salary = np.array([jeff_salary, nick_salary, tom_salary])

In [10]:
jeff_bonus = [500,400,400]
nick_bonus = [600,300,400]
tom_bonus = [200,500,400]
bonus = np.array([jeff_bonus, nick_bonus, tom_bonus])

In [12]:
salary_bonus = base_salary + bonus
print(type(salary_bonus))
print(salary_bonus)

<class 'numpy.ndarray'>
[[3200 3400 3400]
 [3200 3100 3200]
 [2500 3000 2900]]


In [14]:
print(np.amax(salary_bonus, axis = 0))

[3200 3400 3400]


In [22]:
#Maximum Value in Dataset
print(np.amax(np.amax(salary_bonus, axis = 0)))

3400


In [20]:
#Median or Average Method
print(np.average(np.amax(salary_bonus, axis = 0)))

3333.3333333333335
